#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# QLSM — one-liner installer
#
# Usage (HTTP, no domain):
#   curl -fsSL https://raw.githubusercontent.com/dngrtech/qlds-ui/main-docker/qlsm-install.sh | bash
#
# Usage (HTTPS with domain):
#   SITE_ADDRESS=qlds.example.com bash <(curl -fsSL https://raw.githubusercontent.com/dngrtech/qlds-ui/main-docker/qlsm-install.sh)
#
# Environment variables (all optional):
#   SITE_ADDRESS      Domain or :port  (default: :80)
#   VULTR_API_KEY     Vultr API key    (leave blank to skip VM provisioning)
#   INSTALL_DIR       Install path     (default: ~/qlsm)
#   ADMIN_USER        Bootstrap admin  (default: admin)
#   NO_COLOR          Set to any value to disable colour output
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_RAW="https://raw.githubusercontent.com/dngrtech/qlds-ui/main-docker"

# ── Colours (disabled when stdout is not a terminal or NO_COLOR is set) ──────
if [[ -t 1 ]] && [[ -z "${NO_COLOR:-}" ]]; then
    RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
    CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
else
    RED=''; GREEN=''; YELLOW=''; CYAN=''; BOLD=''; RESET=''
fi
info()    { echo -e "${CYAN}==>${RESET} ${BOLD}$*${RESET}"; }
success() { echo -e "${GREEN}✓${RESET}  $*"; }
warn()    { echo -e "${YELLOW}!${RESET}  $*"; }
die()     { echo -e "${RED}✗${RESET}  $*" >&2; exit 1; }

# ── Config from env ───────────────────────────────────────────────────────────
SITE_ADDRESS="${SITE_ADDRESS:-:80}"
VULTR_API_KEY="${VULTR_API_KEY:-}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/qlsm}"
ADMIN_USER="${ADMIN_USER:-admin}"

echo ""
echo -e "${BOLD}  QLSM — Quake Live Server Manager${RESET}"
echo "  https://github.com/dngrtech/qlds-ui"
echo ""

# ── 1. Check dependencies ─────────────────────────────────────────────────────
info "Checking dependencies..."

if ! command -v docker &>/dev/null; then
    die "Docker is not installed. Install it from https://docs.docker.com/get-docker/ and re-run."
fi

# Accept both 'docker compose' (plugin) and 'docker-compose' (standalone)
if docker compose version &>/dev/null 2>&1; then
    COMPOSE="docker compose"
elif command -v docker-compose &>/dev/null; then
    COMPOSE="docker-compose"
else
    die "Docker Compose is not installed. Install it from https://docs.docker.com/compose/install/ and re-run."
fi

if ! command -v curl &>/dev/null; then
    die "curl is not installed. Install it (e.g. apt install curl) and re-run."
fi

if ! command -v openssl &>/dev/null; then
    die "openssl is not installed. Install it (e.g. apt install openssl) and re-run."
fi

success "Docker $(docker --version | awk '{print $3}' | tr -d ',')"
success "Compose (${COMPOSE})"

# ── 2. Create install directory ───────────────────────────────────────────────
info "Creating install directory: ${INSTALL_DIR}"

mkdir -p \
    "${INSTALL_DIR}/data" \
    "${INSTALL_DIR}/configs" \
    "${INSTALL_DIR}/logs" \
    "${INSTALL_DIR}/terraform/ssh-keys" \
    "${INSTALL_DIR}/terraform/vultr-root/terraform.tfstate.d" \
    "${INSTALL_DIR}/ansible/inventory"

cd "${INSTALL_DIR}"
success "Directory ready: ${INSTALL_DIR}"

# ── 3. Download compose files ─────────────────────────────────────────────────
info "Downloading docker-compose.yml..."
curl -fsSL "${REPO_RAW}/docker-compose.yml" -o docker-compose.yml
success "docker-compose.yml"

info "Downloading Caddyfile..."
curl -fsSL "${REPO_RAW}/Caddyfile" -o Caddyfile
success "Caddyfile"

# ── 4. Generate .env ──────────────────────────────────────────────────────────
if [[ -f .env ]]; then
    warn ".env already exists — skipping generation. Edit it manually if needed."
else
    info "Generating .env..."

    REDIS_PASSWORD="$(openssl rand -hex 20)"
    GENERATED_AT="$(date -u '+%Y-%m-%d %H:%M UTC')"

    # Use <<'EOF' to prevent shell expansion of user-supplied values;
    # variables are substituted explicitly via printf.
    printf '# ── QLSM Configuration ──────────────────────────────────────────────────────\n' > .env
    printf '# Generated by qlsm-install.sh on %s\n' "${GENERATED_AT}" >> .env
    printf '# Edit this file and run: %s up -d\n' "${COMPOSE}" >> .env
    printf '# This file contains secrets — keep it private.\n' >> .env
    printf '# ─────────────────────────────────────────────────────────────────────────────\n\n' >> .env
    printf '# Site address — controls HTTPS behaviour (Caddy):\n' >> .env
    printf '#   Domain  -> automatic HTTPS:  SITE_ADDRESS=qlds.example.com\n' >> .env
    printf '#   HTTP only / custom port:     SITE_ADDRESS=:80\n' >> .env
    printf 'SITE_ADDRESS=%s\n\n' "${SITE_ADDRESS}" >> .env
    printf '# Redis password (auto-generated — do not share)\n' >> .env
    printf 'REDIS_PASSWORD=%s\n\n' "${REDIS_PASSWORD}" >> .env
    printf '# Bootstrap admin username (password is '\''admin'\'', change on first login)\n' >> .env
    printf 'DEFAULT_ADMIN_USER=%s\n\n' "${ADMIN_USER}" >> .env
    printf '# Vultr API key — only needed for VM provisioning; leave blank to skip\n' >> .env
    printf 'VULTR_API_KEY=%s\n\n' "${VULTR_API_KEY}" >> .env
    printf '# Optional tuning\n# LOG_LEVEL=INFO\n# JWT_EXPIRATION_HOURS=24\n# GRAFANA_PASSWORD=\n' >> .env

    chmod 600 .env
    success ".env generated (permissions: 600)"
fi

# ── 5. Pull image & start ─────────────────────────────────────────────────────
info "Pulling Docker image (this may take a minute)..."
${COMPOSE} pull

info "Starting QLSM..."
${COMPOSE} up -d

# ── 6. Health check (via Caddy on port 80/443, not the internal Flask port) ───
info "Waiting for QLSM to be ready..."
MAX_WAIT=60
ELAPSED=0

# Determine the health check URL from SITE_ADDRESS
if [[ "$SITE_ADDRESS" == :* ]]; then
    PORT="${SITE_ADDRESS#:}"
    HEALTH_URL="http://localhost:${PORT}/api/instances/ping"
else
    HEALTH_URL="https://${SITE_ADDRESS}/api/instances/ping"
fi

HEALTHY=0
until curl -sf "${HEALTH_URL}" &>/dev/null; do
    if [[ $ELAPSED -ge $MAX_WAIT ]]; then
        break
    fi
    sleep 3
    ELAPSED=$((ELAPSED + 3))
done

if curl -sf "${HEALTH_URL}" &>/dev/null; then
    HEALTHY=1
    success "QLSM is up and healthy"
fi

if [[ $HEALTHY -eq 0 ]]; then
    echo ""
    die "Health check failed after ${MAX_WAIT}s — QLSM did not start correctly.
  Check logs: cd ${INSTALL_DIR} && ${COMPOSE} logs -f web"
fi

# ── 7. Done ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}  Installation complete!${RESET}"
echo ""

if [[ "$SITE_ADDRESS" == :* ]]; then
    PORT="${SITE_ADDRESS#:}"
    echo -e "  URL:       ${BOLD}http://$(hostname -I | awk '{print $1}'):${PORT}${RESET}"
else
    echo -e "  URL:       ${BOLD}https://${SITE_ADDRESS}${RESET}"
fi

echo -e "  Login:     ${BOLD}${ADMIN_USER}${RESET} / ${BOLD}admin${RESET}"
echo -e "  Location:  ${INSTALL_DIR}"
echo ""
echo "  You will be asked to change your password on first login."
echo ""
echo "  Useful commands (run from ${INSTALL_DIR}):"
echo "    ${COMPOSE} logs -f web    # follow logs"
echo "    ${COMPOSE} down           # stop"
echo "    ${COMPOSE} pull && ${COMPOSE} up -d  # update"
echo ""
