"""add lan_rate_enabled to QLInstance

Revision ID: 0165f22b1836
Revises: 20260120120110
Create Date: 2026-01-20 20:20:51.591605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0165f22b1836'
down_revision = '20260120120110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ql_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lan_rate_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ql_instance', schema=None) as batch_op:
        batch_op.drop_column('lan_rate_enabled')

    # ### end Alembic commands ###
