"""add auto_restart_schedule to host

Revision ID: 250d60ffff75
Revises: 5b0d053b6e28
Create Date: 2026-03-03 21:23:39.595017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250d60ffff75'
down_revision = '5b0d053b6e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_restart_schedule', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.drop_column('auto_restart_schedule')

    # ### end Alembic commands ###
