"""Add qlfilter_status to Host model

Revision ID: 4253d4fa556f
Revises: 
Create Date: 2025-05-25 22:42:18.851212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4253d4fa556f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qlfilter_status', sa.Enum('NOT_INSTALLED', 'INSTALLING', 'ACTIVE', 'INACTIVE', 'UNINSTALLING', 'ERROR', 'UNKNOWN', name='qlfilterstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.drop_column('qlfilter_status')

    # ### end Alembic commands ###
