"""add binary metadata

Revision ID: 5531fa448415
Revises: 20260427000000
Create Date: 2026-04-28 14:13:15.036696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5531fa448415'
down_revision = '20260427000000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binary_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_type', sa.String(length=20), nullable=False),
    sa.Column('context_key', sa.String(length=150), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('context_type', 'context_key', 'file_path', name='uq_bm_context_path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('binary_metadata')
    # ### end Alembic commands ###
