"""add api_key and app_setting tables

Revision ID: 6e6df04af542
Revises: 907f3d5860ba
Create Date: 2026-02-25 14:44:11.951098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6df04af542'
down_revision = '907f3d5860ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_plain', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_plain')
    )
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_setting')
    op.drop_table('api_key')
    # ### end Alembic commands ###
