"""add qlx_plugins to qlinstance

Revision ID: 907f3d5860ba
Revises: b45a21ace40f
Create Date: 2026-02-20 23:39:06.167561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907f3d5860ba'
down_revision = 'b45a21ace40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ql_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qlx_plugins', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ql_instance', schema=None) as batch_op:
        batch_op.drop_column('qlx_plugins')

    # ### end Alembic commands ###
