"""add zmq_rcon_port and zmq_rcon_password to QLInstance

Revision ID: a1b2c3d4e5f6
Revises: 0165f22b1836
Create Date: 2026-02-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '0165f22b1836'  # After add_lan_rate_enabled_to_qlinstance
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ql_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zmq_rcon_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('zmq_rcon_password', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ql_instance', schema=None) as batch_op:
        batch_op.drop_column('zmq_rcon_password')
        batch_op.drop_column('zmq_rcon_port')

    # ### end Alembic commands ###
