"""Add zmq_stats_port to QLInstance

Revision ID: b45a21ace40f
Revises: 189f6f89d654
Create Date: 2026-02-12 23:09:15.305394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45a21ace40f'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ql_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zmq_stats_port', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ql_instance', schema=None) as batch_op:
        batch_op.drop_column('zmq_stats_port')

    # ### end Alembic commands ###
