"""increase binary_metadata description to 1000 chars

Revision ID: c940478a96df
Revises: 5531fa448415
Create Date: 2026-04-29 13:51:45.077763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c940478a96df'
down_revision = '5531fa448415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('binary_metadata', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    op.execute(
        "UPDATE binary_metadata SET description = substr(description, 1, 100)"
        " WHERE length(description) > 100"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('binary_metadata', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
