"""add timezone to host

Revision ID: f615fefa2f2e
Revises: f8d0c928c241
Create Date: 2026-03-04 13:58:24.899787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f615fefa2f2e'
down_revision = 'f8d0c928c241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
