---
- name: Sync Common Config Files
  hosts: all
  become: yes
  gather_facts: true

  tasks:
 
    - name: Synchronize files and folders
      synchronize:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        archive: yes
        recursive: yes
      with_items:

        - { src: "../../ql-assets/common/workshop.txt", dest: "/home/ql/qlds/workshop.txt" }
        - { src: "../../configs/{{ target_host }}/mappool.txt", dest: "/home/ql/qlds/mappool.txt" }
        - { src: "../../ql-assets/common/redis.conf", dest: "/home/ql/qlds/redis.conf" }
        

    - name: Set ownership for /home/ql and all subdirectories
      file:
        path: /home/ql
        owner: ql
        group: ql
        recurse: yes
