/**
 * Custom CodeMirror 6 language support for Quake Live Chat Logs.
 * Format generated by minqlx-plugins/log.py:
 * [2026-02-26 03:33:16] [RED_TEAM_CHAT] <brut-:76561198040089156> this one gonna be tuff boys
 * [2026-02-26 03:33:17] [CMD] < :76561197966260715> !teams
 * [2026-02-26 03:40:30] veangance is mine:76561198429256518:87.120.252.225 connected.
 */
import { StreamLanguage, HighlightStyle, syntaxHighlighting } from '@codemirror/language';
import { Tag } from '@lezer/highlight';

// Custom tags scoped to chat logs — won't bleed into other languages
export const chatTags = {
    timestamp: Tag.define(),       // [YYYY-MM-DD HH:MM:SS]
    msgBlueTeam: Tag.define(),     // [BLUE_TEAM_CHAT]
    msgRedTeam: Tag.define(),      // [RED_TEAM_CHAT]
    msgCmd: Tag.define(),          // [CMD]
    genericTag: Tag.define(),      // Any other bracket tag like [CHAT]
    playerName: Tag.define(),      // <playerName:steamId>
    steamId: Tag.define(),         // <playerName:steamId>
    connectionEvent: Tag.define(), // player connected/disconnected
    chatMessage: Tag.define(),     // message text
};

export const chatLogLanguage = StreamLanguage.define({
    name: 'chat-log',

    token(stream) {
        // Skip whitespace
        if (stream.eatSpace()) return null;

        // 1. Timestamps at the beginning of the line: [2026-02-26 03:33:16]
        if (stream.match(/^\[\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\]/)) {
            return 'timestamp';
        }

        // 2. Chat type tags
        if (stream.match(/^\[BLUE_TEAM_CHAT\]/i)) {
            return 'msgBlueTeam';
        }
        if (stream.match(/^\[RED_TEAM_CHAT\]/i)) {
            return 'msgRedTeam';
        }
        if (stream.match(/^\[CMD\]/i)) {
            return 'msgCmd';
        }
        if (stream.match(/^\[[^\]]+\]/)) {
            return 'genericTag'; // Other generic Tags
        }

        // 3. Player tags: <brut-:76561198040089156>
        // Use a state wrapper or simple match. A simple stream match might be tricky 
        // because we want playerName and steamId colored differently.
        // Let's match the '<' first, then match contents.
        if (stream.peek() === '<') {
            stream.next();
            return null; // Return nothing for bracket itself
        }

        // This regex looks ahead to see if we are in a <name:steamid> block
        // It matches up to the colon, ensuring steamId follows before the closing >
        if (stream.match(/^[^:<]+(?=:\d{15,20}>)/)) {
            return 'playerName';
        }

        // Match the steamId and the closing bracket
        if (stream.match(/^:\d{15,20}>/)) {
            // we consume the colon, steamid, and closing bracket as 'steamId'
            return 'steamId';
        }

        // Match name:steamid:ip connected. or disconnected. (name may contain spaces)
        if (stream.match(/^.+:\d{15,20}:[\d.]+ (connected|disconnected)\./)) {
            return 'connectionEvent';
        }

        // Just consume one character at a time for the rest of the message 
        // and return the standard chat message tag (which we will map to white)
        stream.next();
        return 'chatMessage';
    },

    tokenTable: {
        timestamp: chatTags.timestamp,
        msgBlueTeam: chatTags.msgBlueTeam,
        msgRedTeam: chatTags.msgRedTeam,
        msgCmd: chatTags.msgCmd,
        genericTag: chatTags.genericTag,
        playerName: chatTags.playerName,
        steamId: chatTags.steamId,
        connectionEvent: chatTags.connectionEvent,
        chatMessage: chatTags.chatMessage,
    }
});

// Dedicated highlight styles for chat tags — applied without fallback priority
const chatDarkHighlight = HighlightStyle.define([
    { tag: chatTags.timestamp, color: '#546E7A' },
    { tag: chatTags.msgBlueTeam, color: '#4aa5ff', fontWeight: 'bold' },
    { tag: chatTags.msgRedTeam, color: '#ff4a4a', fontWeight: 'bold' },
    { tag: chatTags.msgCmd, color: '#c678dd', fontWeight: 'bold' },
    { tag: chatTags.genericTag, color: '#82aaff' },
    { tag: chatTags.playerName, color: '#e5c07b' },
    { tag: chatTags.steamId, color: '#7f848e' },
    { tag: chatTags.connectionEvent, color: '#98c379', fontStyle: 'italic' },
    { tag: chatTags.chatMessage, color: '#ffffff' },
]);

const chatLightHighlight = HighlightStyle.define([
    { tag: chatTags.timestamp, color: '#6e7781' },
    { tag: chatTags.msgBlueTeam, color: '#0969da', fontWeight: 'bold' },
    { tag: chatTags.msgRedTeam, color: '#cf222e', fontWeight: 'bold' },
    { tag: chatTags.msgCmd, color: '#8250df', fontWeight: 'bold' },
    { tag: chatTags.genericTag, color: '#0550ae' },
    { tag: chatTags.playerName, color: '#953800' },
    { tag: chatTags.steamId, color: '#6e7781' },
    { tag: chatTags.connectionEvent, color: '#116329', fontStyle: 'italic' },
    { tag: chatTags.chatMessage, color: '#24292f' },
]);

export const chatDarkHighlighting = syntaxHighlighting(chatDarkHighlight);
export const chatLightHighlighting = syntaxHighlighting(chatLightHighlight);
