/**
 * Custom CodeMirror 6 language support for MinQLX Logs.
 * Format generated by minqlx's own logger:
 * (21:08:31) [DEBUG @ minqlx.dispatch] client_command(Player(8:'mentor':76561199493333623), 'kill')
 * (21:13:08) [DEBUG @ minqlx.handle_console_print] [ranked] Batch submitted: 70 events, 13 players updated.
 * (01:11:09) [INFO @ minqlx.load_plugin] Loading plugin 'serverchecker'...
 * (01:11:09) [INFO @ minqlx._configure_logger] ===== minqlx run @ 2026-07-09 01:11:09.301584 =====
 */
import { StreamLanguage, HighlightStyle, syntaxHighlighting } from '@codemirror/language';
import { Tag } from '@lezer/highlight';

// Custom tags scoped to minqlx logs — won't bleed into other languages
export const minqlxTags = {
    timestamp: Tag.define(),   // (HH:MM:SS) or ISO datetime in separator lines
    lvlDebug: Tag.define(),    // DEBUG level inside [LEVEL @ module]
    lvlInfo: Tag.define(),     // INFO level inside [LEVEL @ module]
    lvlWarn: Tag.define(),     // WARNING/WARN level inside [LEVEL @ module]
    lvlError: Tag.define(),    // ERROR level inside [LEVEL @ module]
    module: Tag.define(),      // minqlx.dispatch, minqlx.handle_console_print, etc.
    event: Tag.define(),       // client_command, Player, chat, etc. — name before '('
    quoted: Tag.define(),      // 'kill', 'mentor', etc.
    steamId: Tag.define(),     // 17-digit steam64 IDs
    ip: Tag.define(),          // IPv4 addresses
    tag: Tag.define(),         // secondary bracket tags like [ranked], [STAY BONEY]
    ql0: Tag.define(),         // Quake color code ^0
    ql1: Tag.define(),         // Quake color code ^1
    ql2: Tag.define(),         // Quake color code ^2
    ql3: Tag.define(),         // Quake color code ^3
    ql4: Tag.define(),         // Quake color code ^4
    ql5: Tag.define(),         // Quake color code ^5
    ql6: Tag.define(),         // Quake color code ^6
    ql7: Tag.define(),         // Quake color code ^7
    qlCode: Tag.define(),      // the literal ^N marker itself — dimmed near-invisible
};

export const minqlxLogLanguage = StreamLanguage.define({
    name: 'minqlx-log',

    startState() {
        return { inTag: false, qlColor: null };
    },

    token(stream, state) {
        // Reset per-line state at start of line, before eating whitespace
        if (stream.sol()) {
            state.inTag = false;
            state.qlColor = null;
        }

        // Skip whitespace
        if (stream.eatSpace()) return null;

        // 1. Opening of a log tag: [DEBUG @ minqlx.dispatch]
        if (!state.inTag && stream.match(/\[(?=\s*(?:DEBUG|INFO|WARNING|WARN|ERROR)\b\s*@)/i)) {
            state.inTag = true;
            return null;
        }

        // 2. Inside the [LEVEL @ module] tag
        if (state.inTag) {
            if (stream.match(/DEBUG\b/i)) return 'lvlDebug';
            if (stream.match(/(?:WARNING|WARN)\b/i)) return 'lvlWarn';
            if (stream.match(/INFO\b/i)) return 'lvlInfo';
            if (stream.match(/ERROR\b/i)) return 'lvlError';
            if (stream.match(/\s*@\s*/)) return null;
            if (stream.match(/[\w.]+/)) return 'module';
            if (stream.match(/\]/)) {
                state.inTag = false;
                return null;
            }
            stream.next();
            return null;
        }

        // 3. Quake color code: ^0 .. ^7. The literal ^N marker is dimmed to
        // near-invisible; the color it selects persists on the plain text that
        // follows (via the fallthrough) until end-of-line or the next code.
        const ql = stream.match(/\^([0-9])/);
        if (ql) {
            state.qlColor = parseInt(ql[1], 10) & 7;
            return 'qlCode';
        }

        // 4. Timestamp at line start: (21:08:31)
        if (stream.match(/\(\d{2}:\d{2}:\d{2}\)/)) {
            return 'timestamp';
        }

        // 5. ISO datetime, e.g. separator lines: 2026-07-09 01:11:09.301584
        if (stream.match(/\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}(?:\.\d+)?/)) {
            return 'timestamp';
        }

        // 6. Secondary bracket tag: [ranked], [STAY BONEY], ['sound']
        if (stream.match(/\[[^\]\n]+\]/)) {
            return 'tag';
        }

        // 7. Single-quoted string: 'mentor', 'kill'
        if (stream.match(/'[^'\n]*'/)) {
            return 'quoted';
        }

        // 8. IP address: 127.0.0.1
        if (stream.match(/\b\d{1,3}(?:\.\d{1,3}){3}\b/)) {
            return 'ip';
        }

        // 9. SteamID: 17-digit steam64 ID
        if (stream.match(/\b\d{17}\b/)) {
            return 'steamId';
        }

        // 10. Event/function name immediately before a paren: client_command(, Player(
        if (stream.match(/[A-Za-z_][\w.]*(?=\()/)) {
            return 'event';
        }

        // Note: bare integers are intentionally left uncolored — coloring every
        // number turns path segments (ports, Steam appids, workshop content IDs)
        // and file counts blue. Only SteamIDs and IPs get a dedicated color.

        // Fallthrough: consume one character. If a Quake color code is active,
        // keep coloring plain text with it until end-of-line or the next code.
        stream.next();
        return state.qlColor != null ? ('ql' + state.qlColor) : null;
    },

    tokenTable: {
        timestamp: minqlxTags.timestamp,
        lvlDebug: minqlxTags.lvlDebug,
        lvlInfo: minqlxTags.lvlInfo,
        lvlWarn: minqlxTags.lvlWarn,
        lvlError: minqlxTags.lvlError,
        module: minqlxTags.module,
        event: minqlxTags.event,
        quoted: minqlxTags.quoted,
        steamId: minqlxTags.steamId,
        ip: minqlxTags.ip,
        tag: minqlxTags.tag,
        ql0: minqlxTags.ql0,
        ql1: minqlxTags.ql1,
        ql2: minqlxTags.ql2,
        ql3: minqlxTags.ql3,
        ql4: minqlxTags.ql4,
        ql5: minqlxTags.ql5,
        ql6: minqlxTags.ql6,
        ql7: minqlxTags.ql7,
        qlCode: minqlxTags.qlCode,
    }
});

// Dedicated highlight styles for minqlx tags — applied without fallback priority
const minqlxDark = HighlightStyle.define([
    { tag: minqlxTags.timestamp, color: '#7f848e' },
    { tag: minqlxTags.lvlDebug, color: '#7f848e' },
    { tag: minqlxTags.lvlInfo, color: '#98c379' },
    { tag: minqlxTags.lvlWarn, color: '#ffa500' },
    { tag: minqlxTags.lvlError, color: '#ff6b6b', fontWeight: 'bold' },
    { tag: minqlxTags.module, color: '#61afef' },
    { tag: minqlxTags.event, color: '#e5c07b' },
    { tag: minqlxTags.quoted, color: '#98c379' },
    { tag: minqlxTags.steamId, color: '#c678dd' },
    { tag: minqlxTags.ip, color: '#569CD6' },
    { tag: minqlxTags.tag, color: '#56b6c2' },
    { tag: minqlxTags.ql0, color: '#6b6b6b' },
    { tag: minqlxTags.ql1, color: '#ff5555' },
    { tag: minqlxTags.ql2, color: '#5cff5c' },
    { tag: minqlxTags.ql3, color: '#ffff55' },
    { tag: minqlxTags.ql4, color: '#5c7cff' },
    { tag: minqlxTags.ql5, color: '#55ffff' },
    { tag: minqlxTags.ql6, color: '#ff55ff' },
    { tag: minqlxTags.ql7, color: '#ffffff' },
    { tag: minqlxTags.qlCode, color: '#464d5e' },
]);

const minqlxLight = HighlightStyle.define([
    { tag: minqlxTags.timestamp, color: '#6e7781' },
    { tag: minqlxTags.lvlDebug, color: '#6e7781' },
    { tag: minqlxTags.lvlInfo, color: '#116329' },
    { tag: minqlxTags.lvlWarn, color: '#953800' },
    { tag: minqlxTags.lvlError, color: '#cf222e', fontWeight: 'bold' },
    { tag: minqlxTags.module, color: '#0550ae' },
    { tag: minqlxTags.event, color: '#953800' },
    { tag: minqlxTags.quoted, color: '#0a3069' },
    { tag: minqlxTags.steamId, color: '#8250df' },
    { tag: minqlxTags.ip, color: '#0550ae' },
    { tag: minqlxTags.tag, color: '#1b7c83' },
    { tag: minqlxTags.ql0, color: '#24292f' },
    { tag: minqlxTags.ql1, color: '#cf222e' },
    { tag: minqlxTags.ql2, color: '#1a7f37' },
    { tag: minqlxTags.ql3, color: '#9a6700' },
    { tag: minqlxTags.ql4, color: '#0550ae' },
    { tag: minqlxTags.ql5, color: '#1b7c83' },
    { tag: minqlxTags.ql6, color: '#a21caf' },
    { tag: minqlxTags.ql7, color: '#24292f' },
    { tag: minqlxTags.qlCode, color: '#ccd4dc' },
]);

export const minqlxDarkHighlighting = syntaxHighlighting(minqlxDark);
export const minqlxLightHighlighting = syntaxHighlighting(minqlxLight);
